name: 'AI Changelog Generator'
description: 'Generate or update a changelog using AI and open a PR'
author: 'AI'
inputs:
  api_key:
    description: 'API key for the selected AI provider'
    required: true
  api_base_url:
    description: 'Override the base URL for the AI provider'
    required: false
  github_token:
    description: 'GitHub token for pushing commits and creating pull requests'
    required: true
  base_branch:
    description: 'Branch to read commits from'
    default: 'main'
    required: false
  style:
    description: 'Changelog style: summary or full'
    default: 'summary'
    required: false
  provider:
    description: 'AI provider to use (openai, deepseek, anthropic, ollama)'
    default: 'openai'
    required: false
  system_prompt:
    description: 'Optional system prompt to send to the AI model'
    required: false
  model:
    description: 'Optional model identifier for the provider'
    required: false
runs:
  using: 'node20'
  main: 'index.js'
branding:
  icon: 'book'
  color: 'blue'
