name: AI Changelog
on:
  push:
    branches: [main]

jobs:
  changelog:
    if: github.ref != 'refs/heads/generate-ai-changelog'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./
        with:
          api_key: ${{ secrets.AI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          provider: openai
          system_prompt: "You are an AI changelog generator"
          model: gpt-4-turbo
