name: AI Changelog
on:
  push:
    branches: [main]
    paths-ignore:
      - CHANGELOG.md
      - dist/**
      - bin/**

jobs:
  changelog:
    if: github.ref != 'refs/heads/generate-ai-changelog'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npm ci
      - uses: ./
        with:
          api_key: ${{ secrets.AI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          provider: deepseek