name: AI Changelog
on:
  push:
    branches: [main]

jobs:
  changelog:
    if: github.ref != 'refs/heads/generate-ai-changelog'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npm ci
      - uses: ./
        with:
          api_key: ${{ secrets.AI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          system_prompt: "You are a changelog generator, create a short, bullet-point changelog for the provided information"
          provider: deepseek